<?php

namespace App\Enums;

use App\Concerns\HasOptions;

/**
 * Countries by ISO 3166-1 alpha-2 code, plus Kosovo (XK). Cases are in alphabetical order of their labels
 * so options() can feed a select directly.
 */
enum Country: string
{
    use HasOptions;

    case Afghanistan = 'AF';
    case AlandIslands = 'AX';
    case Albania = 'AL';
    case Algeria = 'DZ';
    case AmericanSamoa = 'AS';
    case Andorra = 'AD';
    case Angola = 'AO';
    case Anguilla = 'AI';
    case Antarctica = 'AQ';
    case AntiguaAndBarbuda = 'AG';
    case Argentina = 'AR';
    case Armenia = 'AM';
    case Aruba = 'AW';
    case Australia = 'AU';
    case Austria = 'AT';
    case Azerbaijan = 'AZ';
    case Bahamas = 'BS';
    case Bahrain = 'BH';
    case Bangladesh = 'BD';
    case Barbados = 'BB';
    case Belarus = 'BY';
    case Belgium = 'BE';
    case Belize = 'BZ';
    case Benin = 'BJ';
    case Bermuda = 'BM';
    case Bhutan = 'BT';
    case Bolivia = 'BO';
    case BosniaAndHerzegovina = 'BA';
    case Botswana = 'BW';
    case BouvetIsland = 'BV';
    case Brazil = 'BR';
    case BritishIndianOceanTerritory = 'IO';
    case BritishVirginIslands = 'VG';
    case Brunei = 'BN';
    case Bulgaria = 'BG';
    case BurkinaFaso = 'BF';
    case Burundi = 'BI';
    case Cambodia = 'KH';
    case Cameroon = 'CM';
    case Canada = 'CA';
    case CapeVerde = 'CV';
    case CaribbeanNetherlands = 'BQ';
    case CaymanIslands = 'KY';
    case CentralAfricanRepublic = 'CF';
    case Chad = 'TD';
    case Chile = 'CL';
    case China = 'CN';
    case ChristmasIsland = 'CX';
    case CocosKeelingIslands = 'CC';
    case Colombia = 'CO';
    case Comoros = 'KM';
    case CookIslands = 'CK';
    case CostaRica = 'CR';
    case CoteDIvoire = 'CI';
    case Croatia = 'HR';
    case Cuba = 'CU';
    case Curacao = 'CW';
    case Cyprus = 'CY';
    case Czechia = 'CZ';
    case DemocraticRepublicOfTheCongo = 'CD';
    case Denmark = 'DK';
    case Djibouti = 'DJ';
    case Dominica = 'DM';
    case DominicanRepublic = 'DO';
    case Ecuador = 'EC';
    case Egypt = 'EG';
    case ElSalvador = 'SV';
    case EquatorialGuinea = 'GQ';
    case Eritrea = 'ER';
    case Estonia = 'EE';
    case Eswatini = 'SZ';
    case Ethiopia = 'ET';
    case FalklandIslands = 'FK';
    case FaroeIslands = 'FO';
    case Fiji = 'FJ';
    case Finland = 'FI';
    case France = 'FR';
    case FrenchGuiana = 'GF';
    case FrenchPolynesia = 'PF';
    case FrenchSouthernTerritories = 'TF';
    case Gabon = 'GA';
    case Gambia = 'GM';
    case Georgia = 'GE';
    case Germany = 'DE';
    case Ghana = 'GH';
    case Gibraltar = 'GI';
    case Greece = 'GR';
    case Greenland = 'GL';
    case Grenada = 'GD';
    case Guadeloupe = 'GP';
    case Guam = 'GU';
    case Guatemala = 'GT';
    case Guernsey = 'GG';
    case Guinea = 'GN';
    case GuineaBissau = 'GW';
    case Guyana = 'GY';
    case Haiti = 'HT';
    case HeardIslandAndMcDonaldIslands = 'HM';
    case Honduras = 'HN';
    case HongKong = 'HK';
    case Hungary = 'HU';
    case Iceland = 'IS';
    case India = 'IN';
    case Indonesia = 'ID';
    case Iran = 'IR';
    case Iraq = 'IQ';
    case Ireland = 'IE';
    case IsleOfMan = 'IM';
    case Israel = 'IL';
    case Italy = 'IT';
    case Jamaica = 'JM';
    case Japan = 'JP';
    case Jersey = 'JE';
    case Jordan = 'JO';
    case Kazakhstan = 'KZ';
    case Kenya = 'KE';
    case Kiribati = 'KI';
    case Kosovo = 'XK';
    case Kuwait = 'KW';
    case Kyrgyzstan = 'KG';
    case Laos = 'LA';
    case Latvia = 'LV';
    case Lebanon = 'LB';
    case Lesotho = 'LS';
    case Liberia = 'LR';
    case Libya = 'LY';
    case Liechtenstein = 'LI';
    case Lithuania = 'LT';
    case Luxembourg = 'LU';
    case Macao = 'MO';
    case Madagascar = 'MG';
    case Malawi = 'MW';
    case Malaysia = 'MY';
    case Maldives = 'MV';
    case Mali = 'ML';
    case Malta = 'MT';
    case MarshallIslands = 'MH';
    case Martinique = 'MQ';
    case Mauritania = 'MR';
    case Mauritius = 'MU';
    case Mayotte = 'YT';
    case Mexico = 'MX';
    case Micronesia = 'FM';
    case Moldova = 'MD';
    case Monaco = 'MC';
    case Mongolia = 'MN';
    case Montenegro = 'ME';
    case Montserrat = 'MS';
    case Morocco = 'MA';
    case Mozambique = 'MZ';
    case Myanmar = 'MM';
    case Namibia = 'NA';
    case Nauru = 'NR';
    case Nepal = 'NP';
    case Netherlands = 'NL';
    case NewCaledonia = 'NC';
    case NewZealand = 'NZ';
    case Nicaragua = 'NI';
    case Niger = 'NE';
    case Nigeria = 'NG';
    case Niue = 'NU';
    case NorfolkIsland = 'NF';
    case NorthKorea = 'KP';
    case NorthMacedonia = 'MK';
    case NorthernMarianaIslands = 'MP';
    case Norway = 'NO';
    case Oman = 'OM';
    case Pakistan = 'PK';
    case Palau = 'PW';
    case Palestine = 'PS';
    case Panama = 'PA';
    case PapuaNewGuinea = 'PG';
    case Paraguay = 'PY';
    case Peru = 'PE';
    case Philippines = 'PH';
    case PitcairnIslands = 'PN';
    case Poland = 'PL';
    case Portugal = 'PT';
    case PuertoRico = 'PR';
    case Qatar = 'QA';
    case RepublicOfTheCongo = 'CG';
    case Reunion = 'RE';
    case Romania = 'RO';
    case Russia = 'RU';
    case Rwanda = 'RW';
    case SaintBarthelemy = 'BL';
    case SaintHelenaAscensionAndTristanDaCunha = 'SH';
    case SaintKittsAndNevis = 'KN';
    case SaintLucia = 'LC';
    case SaintMartinFrenchPart = 'MF';
    case SaintPierreAndMiquelon = 'PM';
    case SaintVincentAndTheGrenadines = 'VC';
    case Samoa = 'WS';
    case SanMarino = 'SM';
    case SaoTomeAndPrincipe = 'ST';
    case SaudiArabia = 'SA';
    case Senegal = 'SN';
    case Serbia = 'RS';
    case Seychelles = 'SC';
    case SierraLeone = 'SL';
    case Singapore = 'SG';
    case SintMaarten = 'SX';
    case Slovakia = 'SK';
    case Slovenia = 'SI';
    case SolomonIslands = 'SB';
    case Somalia = 'SO';
    case SouthAfrica = 'ZA';
    case SouthGeorgiaAndSouthSandwichIslands = 'GS';
    case SouthKorea = 'KR';
    case SouthSudan = 'SS';
    case Spain = 'ES';
    case SriLanka = 'LK';
    case Sudan = 'SD';
    case Suriname = 'SR';
    case SvalbardAndJanMayen = 'SJ';
    case Sweden = 'SE';
    case Switzerland = 'CH';
    case Syria = 'SY';
    case Taiwan = 'TW';
    case Tajikistan = 'TJ';
    case Tanzania = 'TZ';
    case Thailand = 'TH';
    case TimorLeste = 'TL';
    case Togo = 'TG';
    case Tokelau = 'TK';
    case Tonga = 'TO';
    case TrinidadAndTobago = 'TT';
    case Tunisia = 'TN';
    case Turkiye = 'TR';
    case Turkmenistan = 'TM';
    case TurksAndCaicosIslands = 'TC';
    case Tuvalu = 'TV';
    case Uganda = 'UG';
    case Ukraine = 'UA';
    case UnitedArabEmirates = 'AE';
    case UnitedKingdom = 'GB';
    case UnitedStates = 'US';
    case UnitedStatesMinorOutlyingIslands = 'UM';
    case UnitedStatesVirginIslands = 'VI';
    case Uruguay = 'UY';
    case Uzbekistan = 'UZ';
    case Vanuatu = 'VU';
    case VaticanCity = 'VA';
    case Venezuela = 'VE';
    case Vietnam = 'VN';
    case WallisAndFutuna = 'WF';
    case WesternSahara = 'EH';
    case Yemen = 'YE';
    case Zambia = 'ZM';
    case Zimbabwe = 'ZW';

    public function label(): string
    {
        return match ($this) {
            self::Afghanistan => 'Afghanistan',
            self::AlandIslands => 'Åland Islands',
            self::Albania => 'Albania',
            self::Algeria => 'Algeria',
            self::AmericanSamoa => 'American Samoa',
            self::Andorra => 'Andorra',
            self::Angola => 'Angola',
            self::Anguilla => 'Anguilla',
            self::Antarctica => 'Antarctica',
            self::AntiguaAndBarbuda => 'Antigua and Barbuda',
            self::Argentina => 'Argentina',
            self::Armenia => 'Armenia',
            self::Aruba => 'Aruba',
            self::Australia => 'Australia',
            self::Austria => 'Austria',
            self::Azerbaijan => 'Azerbaijan',
            self::Bahamas => 'Bahamas',
            self::Bahrain => 'Bahrain',
            self::Bangladesh => 'Bangladesh',
            self::Barbados => 'Barbados',
            self::Belarus => 'Belarus',
            self::Belgium => 'Belgium',
            self::Belize => 'Belize',
            self::Benin => 'Benin',
            self::Bermuda => 'Bermuda',
            self::Bhutan => 'Bhutan',
            self::Bolivia => 'Bolivia',
            self::BosniaAndHerzegovina => 'Bosnia and Herzegovina',
            self::Botswana => 'Botswana',
            self::BouvetIsland => 'Bouvet Island',
            self::Brazil => 'Brazil',
            self::BritishIndianOceanTerritory => 'British Indian Ocean Territory',
            self::BritishVirginIslands => 'British Virgin Islands',
            self::Brunei => 'Brunei',
            self::Bulgaria => 'Bulgaria',
            self::BurkinaFaso => 'Burkina Faso',
            self::Burundi => 'Burundi',
            self::Cambodia => 'Cambodia',
            self::Cameroon => 'Cameroon',
            self::Canada => 'Canada',
            self::CapeVerde => 'Cape Verde',
            self::CaribbeanNetherlands => 'Caribbean Netherlands',
            self::CaymanIslands => 'Cayman Islands',
            self::CentralAfricanRepublic => 'Central African Republic',
            self::Chad => 'Chad',
            self::Chile => 'Chile',
            self::China => 'China',
            self::ChristmasIsland => 'Christmas Island',
            self::CocosKeelingIslands => 'Cocos (Keeling) Islands',
            self::Colombia => 'Colombia',
            self::Comoros => 'Comoros',
            self::CookIslands => 'Cook Islands',
            self::CostaRica => 'Costa Rica',
            self::CoteDIvoire => 'Côte d’Ivoire',
            self::Croatia => 'Croatia',
            self::Cuba => 'Cuba',
            self::Curacao => 'Curaçao',
            self::Cyprus => 'Cyprus',
            self::Czechia => 'Czechia',
            self::DemocraticRepublicOfTheCongo => 'Democratic Republic of the Congo',
            self::Denmark => 'Denmark',
            self::Djibouti => 'Djibouti',
            self::Dominica => 'Dominica',
            self::DominicanRepublic => 'Dominican Republic',
            self::Ecuador => 'Ecuador',
            self::Egypt => 'Egypt',
            self::ElSalvador => 'El Salvador',
            self::EquatorialGuinea => 'Equatorial Guinea',
            self::Eritrea => 'Eritrea',
            self::Estonia => 'Estonia',
            self::Eswatini => 'Eswatini',
            self::Ethiopia => 'Ethiopia',
            self::FalklandIslands => 'Falkland Islands',
            self::FaroeIslands => 'Faroe Islands',
            self::Fiji => 'Fiji',
            self::Finland => 'Finland',
            self::France => 'France',
            self::FrenchGuiana => 'French Guiana',
            self::FrenchPolynesia => 'French Polynesia',
            self::FrenchSouthernTerritories => 'French Southern Territories',
            self::Gabon => 'Gabon',
            self::Gambia => 'Gambia',
            self::Georgia => 'Georgia',
            self::Germany => 'Germany',
            self::Ghana => 'Ghana',
            self::Gibraltar => 'Gibraltar',
            self::Greece => 'Greece',
            self::Greenland => 'Greenland',
            self::Grenada => 'Grenada',
            self::Guadeloupe => 'Guadeloupe',
            self::Guam => 'Guam',
            self::Guatemala => 'Guatemala',
            self::Guernsey => 'Guernsey',
            self::Guinea => 'Guinea',
            self::GuineaBissau => 'Guinea-Bissau',
            self::Guyana => 'Guyana',
            self::Haiti => 'Haiti',
            self::HeardIslandAndMcDonaldIslands => 'Heard Island and McDonald Islands',
            self::Honduras => 'Honduras',
            self::HongKong => 'Hong Kong',
            self::Hungary => 'Hungary',
            self::Iceland => 'Iceland',
            self::India => 'India',
            self::Indonesia => 'Indonesia',
            self::Iran => 'Iran',
            self::Iraq => 'Iraq',
            self::Ireland => 'Ireland',
            self::IsleOfMan => 'Isle of Man',
            self::Israel => 'Israel',
            self::Italy => 'Italy',
            self::Jamaica => 'Jamaica',
            self::Japan => 'Japan',
            self::Jersey => 'Jersey',
            self::Jordan => 'Jordan',
            self::Kazakhstan => 'Kazakhstan',
            self::Kenya => 'Kenya',
            self::Kiribati => 'Kiribati',
            self::Kosovo => 'Kosovo',
            self::Kuwait => 'Kuwait',
            self::Kyrgyzstan => 'Kyrgyzstan',
            self::Laos => 'Laos',
            self::Latvia => 'Latvia',
            self::Lebanon => 'Lebanon',
            self::Lesotho => 'Lesotho',
            self::Liberia => 'Liberia',
            self::Libya => 'Libya',
            self::Liechtenstein => 'Liechtenstein',
            self::Lithuania => 'Lithuania',
            self::Luxembourg => 'Luxembourg',
            self::Macao => 'Macao',
            self::Madagascar => 'Madagascar',
            self::Malawi => 'Malawi',
            self::Malaysia => 'Malaysia',
            self::Maldives => 'Maldives',
            self::Mali => 'Mali',
            self::Malta => 'Malta',
            self::MarshallIslands => 'Marshall Islands',
            self::Martinique => 'Martinique',
            self::Mauritania => 'Mauritania',
            self::Mauritius => 'Mauritius',
            self::Mayotte => 'Mayotte',
            self::Mexico => 'Mexico',
            self::Micronesia => 'Micronesia',
            self::Moldova => 'Moldova',
            self::Monaco => 'Monaco',
            self::Mongolia => 'Mongolia',
            self::Montenegro => 'Montenegro',
            self::Montserrat => 'Montserrat',
            self::Morocco => 'Morocco',
            self::Mozambique => 'Mozambique',
            self::Myanmar => 'Myanmar',
            self::Namibia => 'Namibia',
            self::Nauru => 'Nauru',
            self::Nepal => 'Nepal',
            self::Netherlands => 'Netherlands',
            self::NewCaledonia => 'New Caledonia',
            self::NewZealand => 'New Zealand',
            self::Nicaragua => 'Nicaragua',
            self::Niger => 'Niger',
            self::Nigeria => 'Nigeria',
            self::Niue => 'Niue',
            self::NorfolkIsland => 'Norfolk Island',
            self::NorthKorea => 'North Korea',
            self::NorthMacedonia => 'North Macedonia',
            self::NorthernMarianaIslands => 'Northern Mariana Islands',
            self::Norway => 'Norway',
            self::Oman => 'Oman',
            self::Pakistan => 'Pakistan',
            self::Palau => 'Palau',
            self::Palestine => 'Palestine',
            self::Panama => 'Panama',
            self::PapuaNewGuinea => 'Papua New Guinea',
            self::Paraguay => 'Paraguay',
            self::Peru => 'Peru',
            self::Philippines => 'Philippines',
            self::PitcairnIslands => 'Pitcairn Islands',
            self::Poland => 'Poland',
            self::Portugal => 'Portugal',
            self::PuertoRico => 'Puerto Rico',
            self::Qatar => 'Qatar',
            self::RepublicOfTheCongo => 'Republic of the Congo',
            self::Reunion => 'Réunion',
            self::Romania => 'Romania',
            self::Russia => 'Russia',
            self::Rwanda => 'Rwanda',
            self::SaintBarthelemy => 'Saint Barthélemy',
            self::SaintHelenaAscensionAndTristanDaCunha => 'Saint Helena, Ascension and Tristan da Cunha',
            self::SaintKittsAndNevis => 'Saint Kitts and Nevis',
            self::SaintLucia => 'Saint Lucia',
            self::SaintMartinFrenchPart => 'Saint Martin (French part)',
            self::SaintPierreAndMiquelon => 'Saint Pierre and Miquelon',
            self::SaintVincentAndTheGrenadines => 'Saint Vincent and the Grenadines',
            self::Samoa => 'Samoa',
            self::SanMarino => 'San Marino',
            self::SaoTomeAndPrincipe => 'São Tomé and Príncipe',
            self::SaudiArabia => 'Saudi Arabia',
            self::Senegal => 'Senegal',
            self::Serbia => 'Serbia',
            self::Seychelles => 'Seychelles',
            self::SierraLeone => 'Sierra Leone',
            self::Singapore => 'Singapore',
            self::SintMaarten => 'Sint Maarten',
            self::Slovakia => 'Slovakia',
            self::Slovenia => 'Slovenia',
            self::SolomonIslands => 'Solomon Islands',
            self::Somalia => 'Somalia',
            self::SouthAfrica => 'South Africa',
            self::SouthGeorgiaAndSouthSandwichIslands => 'South Georgia and South Sandwich Islands',
            self::SouthKorea => 'South Korea',
            self::SouthSudan => 'South Sudan',
            self::Spain => 'Spain',
            self::SriLanka => 'Sri Lanka',
            self::Sudan => 'Sudan',
            self::Suriname => 'Suriname',
            self::SvalbardAndJanMayen => 'Svalbard and Jan Mayen',
            self::Sweden => 'Sweden',
            self::Switzerland => 'Switzerland',
            self::Syria => 'Syria',
            self::Taiwan => 'Taiwan',
            self::Tajikistan => 'Tajikistan',
            self::Tanzania => 'Tanzania',
            self::Thailand => 'Thailand',
            self::TimorLeste => 'Timor-Leste',
            self::Togo => 'Togo',
            self::Tokelau => 'Tokelau',
            self::Tonga => 'Tonga',
            self::TrinidadAndTobago => 'Trinidad and Tobago',
            self::Tunisia => 'Tunisia',
            self::Turkiye => 'Türkiye',
            self::Turkmenistan => 'Turkmenistan',
            self::TurksAndCaicosIslands => 'Turks and Caicos Islands',
            self::Tuvalu => 'Tuvalu',
            self::Uganda => 'Uganda',
            self::Ukraine => 'Ukraine',
            self::UnitedArabEmirates => 'United Arab Emirates',
            self::UnitedKingdom => 'United Kingdom',
            self::UnitedStates => 'United States',
            self::UnitedStatesMinorOutlyingIslands => 'United States Minor Outlying Islands',
            self::UnitedStatesVirginIslands => 'United States Virgin Islands',
            self::Uruguay => 'Uruguay',
            self::Uzbekistan => 'Uzbekistan',
            self::Vanuatu => 'Vanuatu',
            self::VaticanCity => 'Vatican City',
            self::Venezuela => 'Venezuela',
            self::Vietnam => 'Vietnam',
            self::WallisAndFutuna => 'Wallis and Futuna',
            self::WesternSahara => 'Western Sahara',
            self::Yemen => 'Yemen',
            self::Zambia => 'Zambia',
            self::Zimbabwe => 'Zimbabwe',
        };
    }
}
